data: ../data/GTSRB_poison
val_split: test
experiment: gtsrb_resnet50_clean
lr: 0.1
warmup_epochs: 0
sched: multistep
decay_milestones:
- 60
- 120
- 160
decay_rate: 0.2
opt: sgd
momentum: 0.9
batch_size: 128
model: resnet50
weight_decay: 5.0e-04
epochs: 200
val_split: test